diamonds_light/cart/urls.py
from django.urls import path
from .views import CartAdd, CartDetail, CartRemove

app_name = 'cart'

urlpatterns = [
    path('', CartDetail.as_view(), name='cart_detail'),
    path('add/<int:product_id>',
         CartAdd.as_view(),
         name='cart_add'
         ),
    path('remove/<int:product_id>',
         CartRemove.as_view(),
         name='cart_remove'),
]

diamonds_light/diamonds_light/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Your API",
      default_version='v1',
      description="Detailed description of your API",
      terms_of_service="https://www.yourwebsite.com/terms/",
      contact=openapi.Contact(email="contact@yourwebsite.com"),
      license=openapi.License(name="Your License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('auth/', include('authentication.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls', namespace='cart'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diamonds_light/cart/models.py
from django.db import models

# Create your models here.

diamonds_light/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

diamonds_light/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from rest_framework.views import APIView


class CartAdd(APIView):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'],
                     )
            # print("is correct!")
            return redirect('cart:cart_detail')


class CartRemove(APIView):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('cart:cart_detail')


class CartDetail(APIView):
    def get(self, request):
        cart = Cart(request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                initial={
                    'quantity': item['quantity'],
                    'update': True,
                }
            )

        return render(request, 'cart/detail.html', {'cart': cart})

diamonds_light/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Корзина покупок
{% endblock %}

{% block content %}
<div>
    <p style="text-align: center; font-weight: bold; font-size: 35px;">Корзина покупок</p>
    <table class="cart">
        <thred>
            <tr class="total">
                <th class="th_center">Картинка</th>
                <th class="th_center">Товар</th>
                <th class="th_center">Обновить кол-во</th>
                <th class="th_center">Удалить</th>
                <th class="th_center">Кол-во</th>
                <th class="th_center">Цена за шт</th>
                <th class="th_center">Общая стоимость</th>
            </tr>
        </thred>
        <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
                         alt="">
                </a>
            </td>
            <td>
                <b style="font-size: 18px;">{{ product.name }}</b>
                <br>
                В наличии:
                {{product.stock}}
            </td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="Обновить">
                    {% csrf_token %}
                </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
            <td style="text-align: center">
                {{ item.quantity }}
            </td>
            <td class="num" style="text-align: center">{{ item.price }}</td>
            <td class="num" style="text-align: center">{{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="3"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <div class="cart" style="margin-bottom: 20px;">
        <td style="background: #ffffff;"><a href="{% url 'home' %}" class="button light" style="height: 60px"> В магазин </a></td>
        <td style="background: #ffffff;"><a href="#" class="button"> Оформить заказ </a></td>
    </div>
</div>
{% endblock %}